---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.yarn-cache
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=generate-image
  - EMBER_TRY_SCENARIO=fastboot-addon-tests

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - yarn global add bower
  - yarn --version
  - bower --version
  - phantomjs --version

install:
  - yarn install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test

addons:
  apt:
    packages:
    - imagemagick
